server:
  port: 8080

spring:
  application:
    name: liveF_ApiGateway
  cloud:
    gateway:
      routes:
        # 인증 서비스
        - id: authServiceRoute
          uri: lb://liveF_Auth-Service
          predicates:
            - Path=/auth/**

        # 커뮤니티 서비스
        - id: communityServiceRoute
          uri: lb://liveF_Community-Service
          predicates:
            - Path=/community/**

        # 데이터 서비스
        - id: dataServiceRoute
          uri: lb://liveF_Data-Service
          predicates:
            - Path=/data/**

eureka:
  client:
    register-with-eureka: true  # 콘솔에 게이트웨이 보이게
    fetch-registry: true        # lb:// 쓰려면 필수
    service-url:
      defaultZone: "http://admin:1234@localhost:8761/eureka"



